name: Build
on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pwd
        run: cd .. && dir

      - name: setup msvc
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake generate
        run: cmake .. -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake ..  --build build --config Release --target GravityGUI
